AWSTemplateFormatVersion: "2010-09-09"
Description: "Creation of Cloudwatch alarm with specified metrics"
Resources:
  SnsTopicMetricFilterCloudWatchAlarm:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        - Endpoint: "Nithyagirish93@gmail.com"
          Protocol: "protocol1"
      TopicName: "alarm-action"
  CloudWatchAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: "cloudwatchalarm-cft-nithya"
      AlarmDescription: "A CloudWatch Alarm that triggers when it reaches greater than threshold."
      MetricName: "metricname1"
      Namespace: "namespace1"
      Statistic: "statistics1"
      Period: "period1"
      EvaluationPeriods: "evaluation1"
      Threshold: "threshold1"
      ComparisonOperator: "operator1"
      AlarmActions:
        - Ref: "SnsTopicMetricFilterCloudWatchAlarm"
      TreatMissingData: "notBreaching"
Parameters: {}
Metadata: {}
Conditions: {}
